### PR TITLE
Fixed AutoSave and Backup-Index

### PR DESCRIPTION
**Pull request by RogerWaters**
This fixes some bugs with file handling.

Fixed:
- AutoSave is now taken into account when loaded as suffix AutoSave is handeled
- Backup has the correct index and is not 1 above current
- Old Backup files are removed correctly

If you have any requirements for refactoring or commenting the code, feel free to ask.
Best regards :)

### CODE REVIEW

**Comment by Elmotrix** [comment]
will this affect existing saves?

**Comment by RogerWaters** [comment]
No, it will still load the default file from the save path.

**Comment by RogerWaters** [comment]
There is still a bug that the atmosphere saved is not the corect instance. => Found this. Will commit fix if tests are successful

**Comment by RogerWaters** [comment]
Found it. The atmosphere was cached in field.

**Comment by Nevcairiel** [comment]
The value was cached because AtmosphericsController.GlobalAtmosphere just returns a reference to an internal static field, so by caching it you avoid creating the grid object on every single lookup, and since its a static reference, it shouldn't change.

And GlobalAtmosphere can be used quite a bunch.

So the real question is, when/why does that static atmosphere reference in AtmosphericsController change? When loading a save? Just clear the backing field during world load, so any old cache gets invalidated.

**Comment by RogerWaters** [comment]
OK I can understand your point in caching the global atmosphere. I proposed another solution to ensure the field is updated with the atmosphere on change.
However I could also not find the reliable entrypoint in code that changes the internal field for global atmosphere.
I have done a test and atmosphere instance is changed on loading a game or starting a new one.

**Comment by Nevcairiel** [comment]
I had a quick look when the global atmosphere is being generated, and it seems to firmly be before StartWorld is called (or ProcessJoinData on clients) - which is where Terraforming starts working.

We should reset the cached global atmosphere in those two patch functions, because the StartWorld patch for example already wants to use it, and it being stale would be no good. And from what I can tell, it should also not change after those ran - unless you load a save, then they should run again.

**Comment by RogerWaters** [comment]
I changed the behavior according to your comments. I'm not playing multiplayer until the next two weeks, but tested with dedicated server. Probably you have the chance to test ist p2p?
Hope this fits your requirements.
Greetings :)

**Comment by Elmotrix** [comment]
i'm merging this. if you have any comments [Nevcairiel](https://github.com/Nevcairiel) shout out :)

**Pull request merged**
